### ISSUE TITLE
Require alignment of grid area names

### ISSUE THREAD

**Issue by firefoxic** [firefoxic/stylelint-config#1]
Multi-line `grid-templat-areas` values:
```css
.selector {
	grid-template-areas:
		"a a"
		"foo foo"
		"long-one long-one";
}
```
should be formatted with area names and closing quotes aligned:
```css
.selector {
	grid-template-areas:
		"a         a       "
		"foo       foo     "
		"long-one  long-one";
}
```
